evething/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    # Authentication things
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name="auth_login"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="auth_logout"),
    url(r'^accounts/register/$', 'thing.views.account_register')
)

urlpatterns += patterns(
    'thing.views',
    url(r'^$', 'home', name='home'),

    (r'^account/$', 'account'),
    (r'^account/change_password/$', 'account_change_password'),
    (r'^account/settings/$', 'account_settings'),
    (r'^account/apikey/add/$', 'account_apikey_add'),
    (r'^account/apikey/delete/$', 'account_apikey_delete'),
    (r'^account/apikey/edit/$', 'account_apikey_edit'),
    (r'^account/apikey/purge/$', 'account_apikey_purge'),
    (r'^account/skillplan/add/$', 'account_skillplan_add'),
    (r'^account/skillplan/delete/$', 'account_skillplan_delete'),
    (r'^account/skillplan/edit/$', 'account_skillplan_edit'),

    (r'^assets/$', 'assets_summary'),
    (r'^assets/filter/$', 'assets_filter'),

    url(r'^blueprints/$', 'blueprints', name='blueprints'),
    (r'^blueprints/add/$', 'blueprints_add'),
    (r'^blueprints/del/$', 'blueprints_del'),
    (r'^blueprints/edit/$', 'blueprints_edit'),
    (r'^blueprints/export/$', 'blueprints_export'),
    (r'^blueprints/import/$', 'blueprints_import'),

    (r'^bpcalc/$', 'bpcalc'),

    (r'^character/(?P<character_name>[\w\'\- ]+)/$', 'character_sheet'),
    (r'^character/(?P<character_name>[\w\'\- ]+)/settings/', 'character_settings'),
    (r'^character/(?P<character_name>[\w\'\- ]+)/mastery/', 'character_mastery'),
    (r'^character/(?P<character_name>[\w\'\- ]+)/skillplan/(?P<skillplan_id>\d+)$', 'character_skillplan'),
    (r'^character_anon/(?P<anon_key>[a-z0-9]+)/$', 'character_anonymous',),
    (r'^character_anon/(?P<anon_key>[a-z0-9]+)/mastery/', 'character_anonymous_mastery'),
    (r'^character_anon/(?P<anon_key>[a-z0-9]+)/skillplan/(?P<skillplan_id>\d+)$', 'character_anonymous_skillplan'),

    (r'^contracts/', 'contracts'),

    (r'^events/$', 'events'),

    (r'^industry/$', 'industry'),

    (r'^mail/$', 'mail'),
    (r'^mail/json/body/(?P<message_id>\d+)/$', 'mail_json_body'),
    (r'^mail/json/headers/$', 'mail_json_headers'),
    (r'^mail/mark_read/$', 'mail_mark_read'),

    (r'^orders/$', 'orders'),

    (r'^trade/$', 'trade'),
    (r'^trade/(?P<year>\d{4})-(?P<month>\d{2})/$', 'trade_timeframe'),
    (r'^trade/(?P<period>all)/$', 'trade_timeframe'),
    (r'^trade/(?P<slug>[-\w]+)/$', 'trade_timeframe'),

    (r'^transactions/$', 'transactions'),

    (r'^wallet_journal/$', 'wallet_journal'),
    (r'^wallet_journal/aggregate/$', 'wallet_journal_aggregate'),
    (r'^wallet_journal/export/$', 'wallet_journal_export'),
    (r'^wallet_journal/graph/single/data/$', 'wallet_journal_graph_single_character_data'),
    (r'^wallet_journal/graph/$', 'wallet_journal_graph_single'),
    

    (r'^pi/$', 'pi'),
)

if getattr(settings, 'ENABLE_GSFAPI', None):
    urlpatterns += patterns('', (r'^gsfapi/', include('gsfapi.urls')))

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    
    # Authentication things
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name="auth_login"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="auth_logout"),
    url(r'^accounts/password_change/$', 'django.contrib.auth.views.password_change', name="auth_password_change"),
    url(r'^accounts/password_change_done/$', 'django.contrib.auth.views.password_change_done'),
)

urlpatterns += patterns('evething.thing.views',
    url(r'^$', 'home', name='home'),

    url(r'^apikeys/$', 'apikeys', name='apikeys'),
    (r'^apikeys/add/$', 'apikeys_add'),
    (r'^apikeys/delete/$', 'apikeys_delete'),
    (r'^apikeys/edit/$', 'apikeys_edit'),

    url(r'^blueprints/$', 'blueprints', name='blueprints'),
    (r'^blueprints/add/$', 'blueprints_add'),

    (r'^bpcalc/$', 'bpcalc'),
    
    url(r'^character/(?P<character_name>[\w\' ]+)/$', 'character', name='character'),
    (r'^character/(?P<character_name>[\w\' ]+)/settings/', 'character_settings'),
    
    (r'^events/$', 'events'),
    
    (r'^orders/$', 'orders'),
    
    (r'^market_scan/$', 'market_scan'),

    (r'^trade/$', 'trade'),
    (r'^trade/(?P<year>\d{4})-(?P<month>\d{2})/$', 'trade_timeframe'),
    (r'^trade/(?P<period>all)/$', 'trade_timeframe'),
    (r'^trade/(?P<slug>[-\w]+)/$', 'trade_timeframe'),
    
    (r'^transactions/$', 'transactions'),
    (r'^transactions/(?P<item_id>all|\d+)/(?P<year>\d{4})-(?P<month>\d{2})/$', 'transactions_item'),
    url(r'^transactions/(?P<item_id>all|\d+)/(?P<period>all)/$', 'transactions_item', name='transactions-all'),
    (r'^transactions/(?P<item_id>all|\d+)/(?P<slug>[-\w]+)/$', 'transactions_item'),
)

# Redirects
urlpatterns += patterns('django.views.generic.simple',
    ('^transactions/(?P<item_id>all|\d+)/$', 'redirect_to', { 'url': '/transactions/%(item_id)s/all/', 'permanent': False }),
)

# If we're running under DEBUG, serve static media files
#if settings.DEBUG:
#    urlpatterns += patterns('',
#        (r'^raidthing_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
#    )

blueprints/models.py
from django.db import models
from django.contrib.auth.models import User

from decimal import *
from everdi.common import commas, nice_time


class Character(models.Model):
	user = models.ForeignKey(User)
	name = models.CharField(max_length=30)
	api_key = models.CharField(max_length=64)
	industry_skill = models.IntegerField(default=0)
	production_efficiency_skill = models.IntegerField(default=0)
	factory_cost = models.DecimalField(max_digits=8, decimal_places=2)
	factory_per_hour = models.DecimalField(max_digits=8, decimal_places=2)
	sales_tax = models.DecimalField(max_digits=4, decimal_places=2)
	brokers_fee = models.DecimalField(max_digits=4, decimal_places=2)
	
	class Meta:
		ordering = ('name',)
	
	def __unicode__(self):
		return self.name

class Item(models.Model):
	id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=128)
	portion_size = models.IntegerField()
	
	sell_median = models.DecimalField(max_digits=15, decimal_places=2)
	buy_median = models.DecimalField(max_digits=15, decimal_places=2)
	
	class Meta:
		ordering = ('name',)
	
	def __unicode__(self):
		return self.name
	
	def nice_sell_median(self):
		return commas(self.sell_median)

class Blueprint(models.Model):
	id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=128)
	item = models.ForeignKey(Item)
	components = models.ManyToManyField(Item, through='BlueprintComponent', related_name='components')
	
	production_time = models.IntegerField()
	productivity_modifier = models.IntegerField()
	material_modifier = models.IntegerField()
	waste_factor = models.IntegerField()
	
	class Meta:
		ordering = ('name',)
	
	def __unicode__(self):
		return self.name

class BlueprintComponent(models.Model):
	blueprint = models.ForeignKey(Blueprint)
	item = models.ForeignKey(Item)
	count = models.IntegerField()
	needs_waste = models.BooleanField()

class BlueprintInstance(models.Model):
	character = models.ForeignKey(Character)
	blueprint = models.ForeignKey(Blueprint)
	material_level = models.IntegerField(default=0)
	productivity_level = models.IntegerField(default=0)
	
	class Meta:
		ordering = ('character', 'blueprint')
	
	def __unicode__(self):
		return "%s's %s" % (self.character.name, self.blueprint.name)
	
	def calc_production_time(self, runs=1, fudge_pl=0):
		# PTM = ProductionTimeModifier = (1 - (0.04 * IndustrySkill)) * ImplantModifier * ProductionSlotModifier
		# ProductionTime (PL>=0) = BaseProductionTime * (1 - (ProductivityModifier / BaseProductionTime) * (PL / (1 + PL)) * PTM
		# ProductionTime (PL<0)  = BaseProductionTime * (1 - (ProductivityModifier / BaseProductionTime) * (PL - 1)) * PTM
		PTM = (1 - (Decimal('0.04') * self.character.industry_skill)) # implement implants/production slots
		BPT = Decimal(self.blueprint.production_time)
		BPM = self.blueprint.productivity_modifier
		PL = Decimal(self.productivity_level + fudge_pl)
		
		if PL >= 0:
			pt = BPT * (1 - (BPM / BPT) * (PL / (1 + PL))) * PTM
		else:
			pt = BPT * (1 - (BPM / BPT) * (PL - 1)) * PTM
		
		pt *= runs
		
		return pt.quantize(Decimal('0'), rounding=ROUND_UP)
	
	def nice_production_time(self, runs=1):
		return nice_time(self.calc_production_time(runs=runs))
	
	def calc_production_cost(self, runs=1, fudge_ml=0, use_sell=False, ):
		"""
from everdi.blueprints.models import *
bpi = BlueprintInstance.objects.all()[0]
bpi.calc_production_cost()
cq = BlueprintComponent.objects.filter(blueprint=bpi.blueprint)
PES = bpi.character.production_efficiency_skill
ML = bpi.material_level
WF = bpi.blueprint.waste_factor
		"""
		
		total_cost = Decimal(0)
		
		# Calculate component costs
		PES = self.character.production_efficiency_skill
		ML = self.material_level + fudge_ml
		WF = self.blueprint.waste_factor
		
		component_queryset = BlueprintComponent.objects.filter(blueprint=self.blueprint)
		for component in component_queryset:
			CC = component.count
			if component.needs_waste:
				amt = round(CC * (1 + ((WF / 100.0) / (ML + 1)) + (0.25 - (0.05 * PES))))
			else:
				amt = CC
			
			amt *= runs
			
			if use_sell is True:
				total_cost += (Decimal(str(amt)) * component.item.sell_median)
			else:
				total_cost += (Decimal(str(amt)) * component.item.buy_median)
		
		# Calculate factory costs
		total_cost += self.character.factory_cost
		
		PT = self.calc_production_time(runs=runs)
		total_cost += (self.character.factory_per_hour * (PT / 3600))
		
		# Calculate taxes and fees
		total_cost = total_cost * (1 + (self.character.sales_tax / 100)) * (1 + (self.character.brokers_fee / 100))
		
		# Run count
		total_cost /= (self.blueprint.item.portion_size * runs)
		
		return total_cost.quantize(Decimal('.01'), rounding=ROUND_UP)
	
	def nice_production_cost(self, runs=1, use_sell=False):
		return commas(self.calc_production_cost(runs=runs, use_sell=use_sell))
	
	#def nice_production_cost_sell(self):
	#	return commas(self.calc_production_cost(use_sell=True))

thing/models/blueprintcomponent.py
# ------------------------------------------------------------------------------
# Copyright (c) 2010-2013, EVEthing team
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#     Redistributions of source code must retain the above copyright notice, this
#       list of conditions and the following disclaimer.
#     Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.
# ------------------------------------------------------------------------------

from django.db import models

from thing.models.blueprint import Blueprint
from thing.models.item import Item
from thing.models.industryjob import IndustryJob


class BlueprintComponent(models.Model):
    """Blueprint components"""
    blueprint = models.ForeignKey(Blueprint)

    activity = models.IntegerField(choices=IndustryJob.ACTIVITY_CHOICES)
    item = models.ForeignKey(Item)
    count = models.IntegerField()
    consumed = models.BooleanField(default=False)

    class Meta:
        app_label = 'thing'

    def __unicode__(self):
        return '%dx %s' % (self.count, self.item.name)

thing/models/contract.py
# ------------------------------------------------------------------------------
# Copyright (c) 2010-2013, EVEthing team
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#     Redistributions of source code must retain the above copyright notice, this
#       list of conditions and the following disclaimer.
#     Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.
# ------------------------------------------------------------------------------

from django.db import models

from thing.models.character import Character
from thing.models.corporation import Corporation
from thing.models.station import Station


class Contract(models.Model):
    character = models.ForeignKey(Character)
    corporation = models.ForeignKey(Corporation, blank=True, null=True)

    contract_id = models.IntegerField(db_index=True)

    issuer_char = models.ForeignKey(Character, blank=True, null=True, related_name='+')
    issuer_corp = models.ForeignKey(Corporation, related_name='+')
    assignee_id = models.IntegerField(default=0)
    acceptor_id = models.IntegerField(default=0)

    start_station = models.ForeignKey(Station, blank=True, null=True, related_name='+')
    end_station = models.ForeignKey(Station, blank=True, null=True, related_name='+')

    type = models.CharField(max_length=16)
    status = models.CharField(max_length=24)
    title = models.CharField(max_length=64)
    for_corp = models.BooleanField(default=False)
    public = models.BooleanField(default=False)

    date_issued = models.DateTimeField()
    date_expired = models.DateTimeField()
    date_accepted = models.DateTimeField(blank=True, null=True)
    date_completed = models.DateTimeField(blank=True, null=True)
    num_days = models.IntegerField()

    price = models.DecimalField(max_digits=15, decimal_places=2)
    reward = models.DecimalField(max_digits=15, decimal_places=2)
    collateral = models.DecimalField(max_digits=15, decimal_places=2)
    buyout = models.DecimalField(max_digits=15, decimal_places=2)
    volume = models.DecimalField(max_digits=16, decimal_places=4)

    retrieved_items = models.BooleanField(default=False)

    class Meta:
        app_label = 'thing'
        ordering = ('-date_issued',)

    def __unicode__(self):
        if self.type == 'Courier':
            return '#%d (%s, %s -> %s)' % (self.contract_id, self.type, self.start_station.short_name, self.end_station.short_name)
        else:
            return '#%d (%s, %s)' % (self.contract_id, self.type, self.start_station.short_name)

    def get_issuer_name(self):
        if self.for_corp:
            return self.issuer_corp.name
        else:
            return self.issuer_char.name

templates/thing/contracts.html
{% extends "base.html" %}
{% import 'macros/icons.html' as icons %}

{% block title %}Contracts{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
      $(document).ready(function () {
        // call the tablesorter plugin
        $("#contracts-table").tablesorter({
          widgets: ['uitheme', 'filter'],
          theme: 'bootstrap',
          widthFixed: true,
          sortList: [[0, 1]],
          headerTemplate : '{content} {icon}'
        });
      });
    </script>
{% endblock %}

{% block content %}
      <div class="row">
        <div class="col-sm-12">
          <h2>Contracts</h2>
          <table id="contracts-table" class="table table-striped table-bordered table-condensed">
            <thead>
              <tr class="c">
                <th>ID</th>
                <th>Issued</th>
                <th>Issued By</th>
                <th>Type</th>
                <th>Status</th>
                <th>Assigned To</th>
                <th>Accepted By</th>
                <th>Last Changed</th>
              </tr>
            </thead>
            <tbody>
              {% for contract in contracts -%}
              <tr>
                <td class="con-id">{{ contract.contract_id }}</td>
                <td class="con-date moment" title="{{ contract.date_issued }}">{{ contract.date_issued }}</td>
                <td class="con-issuer">
                  {% if contract.for_corp -%}
                  {{ icons.corporation() }}
                  {{ contract.issuer_corp.name }}
                  {%- else -%}
                  {{ icons.player() }}
                  {{ contract.issuer_char.name }}
                  {%- endif %}
                </td>
                <td class="c con-type">{{ contract.type }}</td>
                <td class="con-status">
                  {{ icons.contract_status(contract.status) }}
                  {{ contract.status }}
                </td>
                <td class="con-issuer">
                  {% if contract.z_assignee_alliance -%}
                  {{ icons.alliance() }}
                  {{ contract.z_assignee_alliance.name }}
                  {%- elif contract.z_assignee_corp -%}
                  {{ icons.corporation() }}
                  {{ contract.z_assignee_corp.name }}
                  {%- elif contract.z_assignee_char -%}
                  {{ icons.player() }}
                  {{ contract.z_assignee_char.name }}
                  {%- else -%}
                  <span class="fa fa-globe"></span>
                  Public
                  {%- endif %}
                </td>
                <td class="con-issuer">
                  {% if contract.z_acceptor_corp -%}
                  {{ icons.corporation() }}
                  {{ contract.z_acceptor_corp.name }}
                  {%- elif contract.z_acceptor_char -%}
                  {{ icons.player() }}
                  {{ contract.z_acceptor_char.name }}
                  {%- else -%}
                  --
                  {%- endif %}
                </td>
                <td class="con-date moment" title="{% if contract.date_completed -%}
                  {{ contract.date_completed }}
                  {%- elif contract.date_accepted -%}
                  {{ contract.date_accepted }}
                  {%- endif -%}">
                  {% if contract.date_completed -%}
                  {{ contract.date_completed }}
                  {%- elif contract.date_accepted -%}
                  {{ contract.date_accepted }}
                  {%- else -%}
                  --
                  {%- endif %}
                </td>
              </tr>
              {%- else -%}
              <tr>
                <td colspan="8">No contracts.</td>
              </tr>
              {%- endfor %}
            </tbody>
          </table>
        </div>
      </div>
{% endblock %}

templates/thing/industry.html
{% extends "base.html" %}
{% import 'macros/icons.html' as icons %}

{% block extra_js %}
    <script type="text/javascript">$(document).ready(EVEthing.industry.onload);</script>
{% endblock %}

{% block title %}Industry Jobs{% endblock %}

{% block content %}
      <div class="row">
        <div class="col-sm-12">
          <h2>Industry Jobs</h2>

          <ul class="nav nav-tabs">
            <li class="active"><a href="#tab_incomplete" data-toggle="tab">Incomplete</a></li>
            <li><a href="#tab_complete" data-toggle="tab">Complete</a></li>
          </ul>
          <br/>
          <div class="tab-content">
            {#- incomplete -#}
            <div class="tab-pane active" id="tab_incomplete">
              <div class="col-sm-12">
                <table class="table table-striped table-bordered table-condensed" id="incomplete-table">
                  <thead>
                    <tr class="c">
                      <th>Job ID</th>
                      <th>Source</th>
                      <th>Installer</th>
                      <th>Location</th>
                      <th>Type</th>
                      <th>Blueprint</th>
                      <th>Runs</th>
                      <th>Start Time</th>
                      <th>End Time</th>
                      <th>Ready</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for job in incomplete -%}
                    <tr>
                      <td class="industry-jobid">{{ job.job_id }}</td>
                      <td>
                        {% if job.corporation -%}
                        {{ icons.corporation() }}
                        [<span class="tip" rel="tooltip" title="{{ job.corporation.name }}">{{ job.corporation.ticker }}</span>]
                        {%- else -%}
                        {{ icons.player() }}
                        {{ job.character.name }}
                        {%- endif %}
                      </td>
                      <td>
                        {% if job.z_installer -%}
                        {{ icons.player(job.z_installer_mine) }}
                        {{ job.z_installer }}
                        {%- else -%}
                        Unknown installerID: {{ job.installer_id }}
                        {%- endif %}
                      </td>
                      <td>
                        {% if job.z_station -%}
                        <span class="tip" rel="tooltip" title="{{ job.z_station.name }}">{{ job.z_station.short_name }}</span>
                        {%- else -%}
                        {{ job.system.name }}
                        {%- endif %}
                      </td>
                      <td>{{ job.get_activity_display() }}</td>
                      <td>{{ job.blueprint }}</td>
                      <td class="industry-runs">{{ job.runs|commas }}</td>
                      <td class="journal-date moment" title="{{ job.start_date }}">{{ job.start_date }}</td>
                      <td class="journal-date moment" title="{{ job.end_date }}">{{ job.end_date }}</td>
                      <td class="industry-ready">
                        {{ icons.success_fail(job.z_ready) }}
                      </td>
                    </tr>
                    {%- else %}
                    <tr>
                      <td colspan="13">There are no active industry jobs.</td>
                    </tr>
                    {%- endfor %}
                  </tbody>
                </table>
              </div>
            </div>

            {#- complete -#}
            <div class="tab-pane" id="tab_complete">
              <div class="col-sm-12">
                <table class="table table-striped table-bordered table-condensed" id="complete-table">
                  <thead>
                    <tr class="c">
                      <th>Job ID</th>
                      <th>Source</th>
                      <th>Installer</th>
                      <th>Location</th>
                      <th>Type</th>
                      <th>Output</th>
                      <th>Runs</th>
                      <th>Start Time</th>
                      <th>End Time</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for job in complete -%}
                    <tr>
                      <td class="industry-jobid">{{ job.job_id }}</td>
                      <td>
                        {% if job.corporation -%}
                        {{ icons.corporation() }}
                        [<span class="tip" rel="tooltip" title="{{ job.corporation.name }}">{{ job.corporation.ticker }}</span>]
                        {%- else -%}
                        {{ icons.player() }}
                        {{ job.character.name }}
                        {%- endif %}
                      </td>
                      <td>
                        {% if job.z_installer -%}
                        {{ icons.player(job.z_installer_mine) }}
                        {{ job.z_installer }}
                        {%- else -%}
                        Unknown installerID: {{ job.installer_id }}
                        {%- endif %}
                      </td>
                      <td>
                        {% if job.z_station -%}
                        <span class="tip" rel="tooltip" title="{{ job.z_station.name }}">{{ job.z_station.short_name }}</span>
                        {%- else -%}
                        {{ job.system.name }}
                        {%- endif %}
                      </td>
                      <td>{{ job.get_activity_display() }}</td>
                      <td>{{ job.product }}</td>
                      <td class="industry-runs">{{ job.runs|commas }}</td>
                      <td class="journal-date moment" title="{{ job.start_date }}">{{ job.start_date }}</td>
                      <td class="journal-date moment" title="{{ job.end_date }}">{{ job.end_date }}</td>
                      <td class="industry-status">{{ job.get_status_display() }}</td>
                    </tr>
                    {%- else %}
                    <tr>
                      <td colspan="13">No complete jobs</td>
                    </tr>
                    {%- endfor %}
                  </tbody>
                </table>
              </div>            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/thing/trade.html
{% extends "base.html" %}

{% block title %}Trade{% endblock %}

{% block content %}
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2>Trade Results</h2>
          <table class="table table-striped table-bordered table-condensed">
            <thead>
              <tr class="c">
                <th class="l">Time Period</th>
                <th>Buy Total</th>
                <th>Sell Total</th>
                <th>Balance</th>
              </tr>
            </thead>
            <tbody>
              {% for transaction in transactions -%}
              <tr class="r">
                <td class="l"><a href="{{ url('thing.views.trade_timeframe', transaction.urlpart) }}">{{ transaction.name }}</a></td>
                <td>{{ transaction.buy_total|commas }}</td>
                <td>{{ transaction.sell_total|commas }}</td>
                <td>{{ transaction.balance|commas|balance|safe }}</td>
              </tr>
              {%- else -%}
              <tr>
                <td colspan="4">No transactions found.</td>
              </tr>
              {%- endfor %}
            </tbody>
          </table>
        </div>
      </div>
{% endblock %}